- hosts: localhost
  gather_facts: no
  vars_files:
       - keys.yml
  tasks:
       - name: Create a VPC with dedicated tenancy
         ec2_vpc_net:
             aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
             aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
             ec2_region: "{{ AWS_REGION }}"
             name: NewVPC
             cidr_block: 10.10.0.0/16
             tags:
               client: LA
             tenancy: dedicated


             