- hosts: localhost
  gather_facts: no
  vars_files:
       - keys.yml
  tasks:
       - name: Create new security group
         ec2_group:
             aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
             aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
             ec2_region: "{{ AWS_REGION }}"
             name: demoSG
             description: An example of EC2 security group
             vpc_id: vpc-ed1b7f97
             rules:
               - proto: tcp
                 ports:
                    - 80
                    - 443
                 cidr_ip: 0.0.0.0/0
               - proto: tcp
                 to_port:
                    - 22
                 cidr_ip: 86.75.30.9/32
             rules_egress:
               - proto: tcp
                 from_port: 22  
                 cidr_ip: 0.0.0.0/0
                
